-- Your SQL goes here
CREATE TABLE babies (
  id VARCHAR(50) PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  sex TEXT NOT NULL,
  birthday TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
