-- Your SQL goes here
CREATE TABLE IF NOT EXISTS notes (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  baby_id INTEGER NOT NULL,
  note TEXT,
  image BLOB,
  file BLOB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (baby_id)
    REFERENCES babies (id)
);
